cmake_minimum_required(VERSION 3.22.1)
project(trackmr_openxr LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(OpenXR REQUIRED CONFIG)
add_library(trackmr_openxr SHARED session.cpp)
target_include_directories(trackmr_openxr PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/../../../../render/include")
target_compile_definitions(trackmr_openxr PRIVATE XR_USE_PLATFORM_ANDROID XR_USE_GRAPHICS_API_OPENGL_ES)
target_compile_options(trackmr_openxr PRIVATE -Wall -Wextra -Werror=return-type)
target_link_libraries(trackmr_openxr OpenXR::openxr_loader EGL GLESv3 android log)
target_link_options(trackmr_openxr PRIVATE "-Wl,-z,max-page-size=16384")
